import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import http from 'node:http';
import {createContentStore,localAdminPlugin} from '../build/local-admin.mjs';
const base=path.resolve('work/admin-tests');
async function fixture(t){await fs.mkdir(base,{recursive:true});const root=await fs.mkdtemp(path.join(base,'case-'));t.after(async()=>{assert.ok(root.startsWith(base+path.sep));await fs.rm(root,{recursive:true,force:true})});return root}
const entry={slug:'test-article',title:'مقال للاختبار',description:'وصف',category:'برمجة',date:'2026-09-24',published:false,tags:['Git'],paragraphs:[{heading:'الفكرة',text:'محتوى المقال'},{code:'console.log(1)'}],references:[{title:'Git',url:'https://git-scm.com'}]};
test('persists drafts, publishes updates, preserves rich content and backs up previous versions',async t=>{const root=await fixture(t),store=createContentStore(root);const draft=await store.save({kind:'articles',entry,revision:null,originalSlug:null});const afterRestart=await createContentStore(root).list();assert.equal(afterRestart.length,1);assert.equal(afterRestart[0].entry.published,false);assert.deepEqual(afterRestart[0].entry.paragraphs,entry.paragraphs);const published=await store.save({kind:'articles',entry:{...entry,published:true},revision:draft.revision,originalSlug:entry.slug});assert.equal(published.entry.published,true);assert.notEqual(published.revision,draft.revision);assert.equal((await fs.readdir(path.join(root,'work/content-backups/articles'))).length,1);assert.match(await fs.readFile(path.join(root,'content/index.ts'),'utf8'),/filter\(e=>e.published\)/);await store.save({kind:'articles',entry,revision:published.revision,originalSlug:entry.slug});assert.equal((await store.list())[0].entry.published,false)});
test('rejects duplicates, stale updates, unsafe slugs, unsafe reference links and incomplete publication',async t=>{const root=await fixture(t),store=createContentStore(root);const input={kind:'articles',entry,revision:null,originalSlug:null};const saved=await store.save(input);await assert.rejects(store.save(input),{status:409});await assert.rejects(store.save({...input,originalSlug:entry.slug,revision:'stale'}),{status:409});await assert.rejects(store.save({...input,entry:{...entry,slug:'../../outside'}}),{status:400});await assert.rejects(store.save({...input,entry:{...entry,slug:'unsafe',references:[{title:'bad',url:'javascript:alert(1)'}]}}),{status:400});await assert.rejects(store.save({...input,entry:{...entry,slug:'empty',published:true,paragraphs:[]}}),{status:400});assert.equal((await store.list())[0].revision,saved.revision)});
test('prompt text is stored exactly including placeholders and line breaks',async t=>{const root=await fixture(t),store=createContentStore(root);const prompt='اشرح [CODE]\n\nالهدف: [GOAL]\nلا تغيّر الكود.';await store.save({kind:'prompts',entry:{...entry,slug:'test-prompt',prompt,published:true},originalSlug:null,revision:null});assert.equal((await createContentStore(root).list())[0].entry.prompt,prompt)});
test('local endpoint blocks foreign hosts, origins and missing tokens',async t=>{const root=await fixture(t);let middleware;localAdminPlugin().configureServer({config:{root},middlewares:{use(_path,fn){middleware=fn}}});const server=http.createServer((req,res)=>middleware(req,res));await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>server.close(r)));const address=server.address();const url=`http://127.0.0.1:${address.port}/api/local-admin`;const request=(options={})=>new Promise((resolve,reject)=>{const req=http.request(url,{method:options.method||'GET',headers:{Host:'localhost:5173',...options.headers}},res=>{let body='';res.on('data',c=>body+=c);res.on('end',()=>resolve({status:res.statusCode,json:async()=>JSON.parse(body)}))});req.on('error',reject);req.end(options.body)});assert.equal((await fetch(url)).status,403);assert.equal((await request({headers:{Origin:'https://evil.example'}})).status,403);assert.equal((await request({method:'POST',headers:{Origin:'http://localhost:5173','Content-Type':'application/json'},body:'{}'})).status,403);const session=await (await request()).json();const response=await request({method:'POST',headers:{Origin:'http://localhost:5173','Content-Type':'application/json','X-Admin-Token':session.token},body:JSON.stringify({kind:'articles',entry,revision:null,originalSlug:null})});assert.equal(response.status,200);assert.equal((await response.json()).saved.entry.title,entry.title)});

