const Link = (props: React.AnchorHTMLAttributes<HTMLAnchorElement>) => <a {...props}/>;
import {notFound} from 'next/navigation';
import {content,entries} from '@/content';
import {Kind,sections} from '@/content/schema';
import CopyPromptButton from '@/components/CopyPromptButton';
export function generateStaticParams(){return Object.entries(content).flatMap(([section,list])=>list.filter(e=>e.published).map(e=>({section,slug:e.slug})))}
async function record(params:Promise<{section:string;slug:string}>){const {section,slug}=await params;if(!(section in sections))notFound();const item=entries(section as Kind).find(e=>e.slug===slug);if(!item)notFound();return {item,section:section as Kind}}
export async function generateMetadata({params}:{params:Promise<{section:string;slug:string}>}){const {item,section}=await record(params);const url=`/${section}/${item.slug}`;return {title:item.title,description:item.description,alternates:{canonical:url},openGraph:{title:item.title,description:item.description,url,type:section==='articles'?'article':'website'},twitter:{card:'summary',title:item.title,description:item.description}}}
export default async function Detail({params}:{params:Promise<{section:string;slug:string}>}){const {item,section}=await record(params);return <><header className="wrap page-head"><Link className="eyebrow" href={`/${section}`}>↗ {sections[section].title}</Link><span className="meta">{item.category} {item.sample?' / محتوى تجريبي':''}</span><h1>{item.title}</h1><p>{item.description}</p><div className="meta" style={{marginTop:25}}><time dateTime={item.date}>{item.date}</time>{item.minutes?` · ${item.minutes} دقائق قراءة`:''}</div></header>{item.prompt?<div className="wrap"><div className="reading"><h2>شو بيعمل هذا البرومبت؟</h2><p>{item.description}</p><h2>متى تستخدمه؟</h2><p>{item.when}</p><p>بدّل المتغيّرات بين الأقواس بمعلوماتك. راجع الردود ولا تشارك أسرارًا أو مفاتيح وصول.</p><div className="prompt-box">{item.prompt.split(/(\[[A-Z_]+\])/g).map((part,i)=>part.startsWith('[')?<mark key={i} dir="ltr">{part}</mark>:part)}</div><CopyPromptButton text={item.prompt}/></div></div>:<section className="paper"><article className="reading">{item.issuer&&<p>الجهة المانحة: {item.issuer}</p>}{item.year&&<p>السنة: {item.year}</p>}{item.technologies&&<p dir="ltr">{item.technologies.join(" · ")}</p>}{item.github&&<p><a href={item.github}>المستودع على GitHub ↗</a></p>}{item.demo&&<p><a href={item.demo}>جرّب المشروع ↗</a></p>}{item.credential&&<p><a href={item.credential}>تحقّق من الشهادة ↗</a></p>}{item.image&&<img src={item.image} alt={item.title} loading="lazy" style={{maxWidth:"100%",height:"auto"}}/>}{item.paragraphs?.map((block,i)=><section key={i}>{block.heading&&<h2>{block.heading}</h2>}{block.text&&<p>{block.text}</p>}{block.code&&<pre><code>{block.code}</code></pre>}{block.quote&&<blockquote>{block.quote}</blockquote>}</section>)}{item.references&&<><h2>كمّل من المصدر</h2>{item.references.map(ref=><p key={ref.url}><a href={ref.url} target="_blank" rel="noreferrer">{ref.title} ↗</a></p>)}</>}</article></section>}<aside className="wrap related"><h2>خيط آخر تتبعه.</h2>{entries(section).filter(e=>e.slug!==item.slug).slice(0,2).map(e=><Link href={`/${section}/${e.slug}`} key={e.slug}>{e.title} ↖</Link>)}<Link href={`/${section}`}>ارجع إلى المكتبة ↗</Link></aside></>}

