'use client';

import {useEffect,useState} from 'react';
import Link from 'next/link';
import type {Entry} from '@/content/schema';
import CopyPromptButton from '@/components/CopyPromptButton';

type Kind='articles'|'prompts';
type RecordItem={kind:Kind;entry:Entry;revision:string};
type Editor={kind:Kind;entry:Entry;revision:string|null;originalSlug:string|null};
const blank=(kind:Kind):Editor=>({kind,revision:null,originalSlug:null,entry:{slug:'',title:'',description:'',category:'',date:new Date().toLocaleDateString('en-CA'),published:false,tags:[],sample:false,...(kind==='articles'?{minutes:3,paragraphs:[{heading:'',text:''}]}:{prompt:'',when:''})}});

export default function AdminDashboard(){
 const [items,setItems]=useState<RecordItem[]>([]),[token,setToken]=useState(''),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState('');
 const [editor,setEditor]=useState<Editor|null>(null),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[preview,setPreview]=useState(false),[query,setQuery]=useState(''),[filter,setFilter]=useState('all');
 async function load(){setLoading(true);setLoadError('');try{const response=await fetch('/api/local-admin',{cache:'no-store'});if(!response.ok)throw new Error();const data=await response.json() as {items:RecordItem[];token:string};if(!Array.isArray(data.items)||!data.token)throw new Error();setItems(data.items);setToken(data.token);}catch{setLoadError('لوحة الإدارة تعمل مع النسخة المحلية على جهازك. شغّل الموقع محليًا ثم أعد المحاولة. إدارة النسخة المستضافة تحتاج ربط تسجيل دخول وتخزين دائم.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 useEffect(()=>{if(!dirty)return;const guard=(event:BeforeUnloadEvent)=>{event.preventDefault();event.returnValue=''};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard)},[dirty]);
 function canLeave(){return !dirty||window.confirm('عندك تعديلات غير محفوظة. تتركها وتكمل؟')}
 function open(value:Editor|null){if(busy||!canLeave())return;setEditor(value);setDirty(false);setPreview(false);setError('');setMessage('');window.scrollTo({top:0,behavior:'instant'})}
 function update(patch:Partial<Entry>){setEditor(current=>current?{...current,entry:{...current.entry,...patch}}:null);setDirty(true);setMessage('');setError('')}
 function block(index:number,patch:NonNullable<Entry['paragraphs']>[number]){if(!editor)return;update({paragraphs:editor.entry.paragraphs?.map((p,i)=>i===index?{...p,...patch}:p)})}
 async function save(published:boolean){if(!editor||busy)return;setBusy(true);setError('');setMessage('');try{const response=await fetch('/api/local-admin',{method:'POST',headers:{'Content-Type':'application/json','X-Admin-Token':token},body:JSON.stringify({...editor,entry:{...editor.entry,published}})});const data=await response.json() as {saved:RecordItem;error?:string};if(!response.ok)throw new Error(data.error||'تعذّر الحفظ.');const saved=data.saved as RecordItem;setEditor({...saved,originalSlug:saved.entry.slug});setItems(old=>[saved,...old.filter(i=>!(i.kind===saved.kind&&i.entry.slug===saved.entry.slug))]);setDirty(false);setMessage(published?'تم النشر على الموقع المحلي. الرابط جاهز.':'تم حفظ المسودة. لن تظهر للزوار.');}catch(err){setError(err instanceof Error?err.message:'تعذّر الحفظ. لم نفقد النص الموجود في المحرر.')}finally{setBusy(false)}}
 async function copyLink(){if(!editor)return;try{await navigator.clipboard.writeText(`${window.location.origin}/${editor.kind}/${encodeURIComponent(editor.entry.slug)}`);setMessage('تم نسخ الرابط. هذا رابط محلي يعمل على جهازك حاليًا.')}catch{setError('تعذّر نسخ الرابط. افتح الصفحة وانسخ عنوانها من المتصفح.')}}
 const visible=items.filter(i=>(filter==='all'||filter===i.kind||(filter==='draft'&&!i.entry.published))&&`${i.entry.title} ${i.entry.category} ${i.entry.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase()));
 const current=editor?.entry;
 return <div className="admin wrap">
 <div className="admin-top"><div><span className="eyebrow">مساحتك الخاصة / إدارة المحتوى</span><h1>{editor?(editor.originalSlug?'تعديل المحتوى':'فكرة جديدة.'):'من الفكرة إلى النشر.'}</h1><p>{editor?'اكتب على مهلك. احفظ مسودة، وانشر لما تكون جاهز.':'مقالاتك وبرومبتاتك، كلها من مكان واحد.'}</p></div><Link href="/" className="admin-btn secondary">عرض الموقع ↗</Link></div>
 <div className="admin-notice"><span>على هذا الجهاز</span> التغييرات تُحفظ في المشروع نفسه. النشر هنا يظهر في الموقع المحلي؛ رابط الإنترنت غير مفعّل بعد.</div>
 {loading?<p role="status" className="admin-empty">جارٍ تحميل المحتوى…</p>:loadError?<div className="admin-empty" role="alert"><p>{loadError}</p><button className="admin-btn" onClick={()=>void load()}>إعادة المحاولة</button></div>:<>
 {!editor?<><div className="admin-stats"><div><strong>{items.filter(i=>i.kind==='articles').length}</strong><span>مقالات</span></div><div><strong>{items.filter(i=>i.kind==='prompts').length}</strong><span>برومبتات</span></div><div><strong>{items.filter(i=>!i.entry.published).length}</strong><span>مسودات</span></div></div><div className="admin-toolbar"><div className="admin-actions"><button className="admin-btn" onClick={()=>open(blank('articles'))}>+ مقال جديد</button><button className="admin-btn secondary" onClick={()=>open(blank('prompts'))}>+ برومبت جديد</button></div><label className="admin-search"><span className="sr-only">ابحث في المحتوى</span><input placeholder="ابحث بعنوان أو تصنيف…" value={query} onChange={e=>setQuery(e.target.value)}/></label></div><div className="admin-filters" aria-label="تصفية المحتوى">{[['all','الكل'],['articles','المقالات'],['prompts','البرومبتات'],['draft','المسودات']].map(([value,label])=><button key={value} aria-pressed={filter===value} onClick={()=>setFilter(value)}>{label}</button>)}</div><div className="admin-list">{visible.length?visible.map(item=><div className="admin-item" key={item.kind+item.entry.slug}><div><span className="admin-item-meta">{item.kind==='articles'?'مقال':'برومبت'} · {item.entry.category||'بدون تصنيف'} <span className={item.entry.published?'status published':'status'}>{item.entry.published?'منشور':'مسودة'}</span>{item.entry.sample&&<span className="status">تجريبي</span>}</span><h2>{item.entry.title}</h2><span className="admin-date">{item.entry.date}</span></div><div className="admin-actions"><button className="admin-btn secondary" onClick={()=>open({...item,entry:structuredClone(item.entry),originalSlug:item.entry.slug})}>تعديل</button>{item.entry.published&&<a href={`/${item.kind}/${item.entry.slug}`} target="_blank" rel="noreferrer" className="admin-link">عرض ↗</a>}</div></div>):<p className="admin-empty">{items.length?'ما في محتوى يطابق البحث.':'ابدأ بأول مقال أو برومبت.'}</p>}</div></>:current&&<>
 <div className="admin-editor-bar"><button className="admin-link" disabled={busy} onClick={()=>open(null)}>→ كل المحتوى</button><div className="admin-actions"><span className="admin-date">{dirty?'تعديلات غير محفوظة':editor.originalSlug?'كل التعديلات محفوظة':'لم يُحفظ بعد'}</span><button className="admin-btn secondary" aria-pressed={preview} onClick={()=>setPreview(!preview)}>{preview?'رجوع للمحرر':'معاينة'}</button></div></div>
 {error&&<p role="alert" className="admin-feedback error">{error}</p>}{message&&<p role="status" className="admin-feedback">{message}</p>}
 {preview?<article className="admin-preview"><span className="eyebrow">معاينة {current.published?'المحتوى':'المسودة'} / {current.category}</span><h2>{current.title||'عنوانك يظهر هون'}</h2><p className="admin-preview-description">{current.description}</p><span className="meta">{current.date}{current.minutes?` · ${current.minutes} دقائق`:''}</span>{editor.kind==='prompts'?<><h3>متى تستخدمه؟</h3><p>{current.when}</p><div className="prompt-box">{(current.prompt||'نص البرومبت يظهر هون.').split(/(\[[A-Z_]+\])/g).map((part,i)=>part.startsWith('[')?<mark key={i} dir="ltr">{part}</mark>:part)}</div><CopyPromptButton text={current.prompt||''}/></>:<div className="reading">{current.paragraphs?.map((p,i)=><section key={i}>{p.heading&&<h3>{p.heading}</h3>}{p.text&&<p>{p.text}</p>}{p.code&&<pre dir="ltr"><code>{p.code}</code></pre>}{p.quote&&<blockquote>{p.quote}</blockquote>}</section>)}</div>}{!!current.references?.length&&<><h3>المراجع</h3>{current.references.map((ref,i)=><p key={i}>{/^https?:\/\//.test(ref.url)?<a href={ref.url} target="_blank" rel="noreferrer">{ref.title||ref.url} ↗</a>:ref.title}</p>)}</>}</article>:<form id="content-editor" onSubmit={e=>{e.preventDefault();void save(true)}} className="admin-form"><fieldset disabled={busy}>
 <div className="admin-form-grid"><label className="admin-wide">العنوان <span>*</span><input required maxLength={300} placeholder={editor.kind==='articles'?'شو المشكلة اللي بدك تحكي عنها؟':'برومبت لفهم كود جديد'} value={current.title} onChange={e=>update({title:e.target.value})}/></label><label>رابط الصفحة <span>*</span><input dir="ltr" required readOnly={!!editor.originalSlug} maxLength={100} placeholder="understand-code" value={current.slug} onChange={e=>update({slug:e.target.value.toLowerCase().replace(/\s+/g,'-')})}/><small dir="ltr">/{editor.kind}/{current.slug||'your-title'}</small><small>{editor.originalSlug?'الرابط ثابت حتى تظل الروابط القديمة تعمل.':'حروف أو أرقام، وافصل الكلمات بشرطة -'}</small></label><label>التصنيف<input maxLength={100} placeholder="أدوات المبرمج" value={current.category} onChange={e=>update({category:e.target.value})}/></label><label className="admin-wide">وصف مختصر<textarea rows={3} maxLength={2000} placeholder="شو رح يفهم القارئ أو يستفيد؟" value={current.description} onChange={e=>update({description:e.target.value})}/></label><label>التاريخ <span>*</span><input required type="date" value={current.date} onChange={e=>update({date:e.target.value})}/></label>{editor.kind==='articles'&&<label>وقت القراءة بالدقائق<input type="number" min={1} max={999} value={current.minutes||1} onChange={e=>update({minutes:Number(e.target.value)||1})}/></label>}<label className="admin-wide">الكلمات المفتاحية<input placeholder="Git، أدوات، برمجة" value={current.tags.join('، ')} onChange={e=>update({tags:e.target.value.split(/[,،]/).map(t=>t.trim())})}/><small>افصل الكلمات بفاصلة.</small></label></div>
 {editor.kind==='prompts'?<section className="admin-form-section"><h2>البرومبت</h2><label>متى تستخدمه؟<textarea rows={3} value={current.when||''} onChange={e=>update({when:e.target.value})}/></label><label>النص الذي سينسخه الزائر<textarea className="admin-prompt-input" rows={15} dir="auto" placeholder={'اكتب البرومبت كاملًا…\nاستخدم [CODE] أو [GOAL] للمتغيرات.'} value={current.prompt||''} onChange={e=>update({prompt:e.target.value})}/><small>زر النسخ يُضاف تلقائيًا في صفحة البرومبت.</small></label></section>:<section className="admin-form-section"><h2>محتوى المقال</h2><p className="admin-help">رتّب فكرتك على فقرات. تقدر تضيف عنوانًا أو مثال كود أو اقتباسًا لكل فقرة.</p>{current.paragraphs?.map((p,i)=><div className="admin-block" key={i}><div className="admin-block-head"><strong>الفقرة {i+1}</strong><div className="admin-actions"><button type="button" className="admin-link" aria-label={`نقل الفقرة ${i+1} للأعلى`} disabled={i===0} onClick={()=>{const paragraphs=[...(current.paragraphs||[])];[paragraphs[i-1],paragraphs[i]]=[paragraphs[i],paragraphs[i-1]];update({paragraphs})}}>↑</button><button type="button" className="admin-link" aria-label={`نقل الفقرة ${i+1} للأسفل`} disabled={i===(current.paragraphs?.length||0)-1} onClick={()=>{const paragraphs=[...(current.paragraphs||[])];[paragraphs[i+1],paragraphs[i]]=[paragraphs[i],paragraphs[i+1]];update({paragraphs})}}>↓</button><button type="button" className="admin-link" onClick={()=>{if((!p.text&&!p.heading&&!p.code&&!p.quote)||window.confirm('إزالة هذه الفقرة من المحرر؟ لن تتغير النسخة المحفوظة قبل الحفظ.'))update({paragraphs:current.paragraphs?.filter((_,j)=>j!==i)})}}>إزالة</button></div></div><label>عنوان فرعي (اختياري)<input value={p.heading||''} onChange={e=>block(i,{heading:e.target.value})}/></label><label>نص الفقرة<textarea rows={5} value={p.text||''} onChange={e=>block(i,{text:e.target.value})}/></label><details open={!!p.code||!!p.quote}><summary>كود أو اقتباس (اختياري)</summary><label>مثال الكود<textarea dir="ltr" rows={5} className="admin-code-input" value={p.code||''} onChange={e=>block(i,{code:e.target.value})}/></label><label>اقتباس<textarea rows={2} value={p.quote||''} onChange={e=>block(i,{quote:e.target.value})}/></label></details></div>)}<button type="button" className="admin-btn secondary" onClick={()=>update({paragraphs:[...(current.paragraphs||[]),{heading:'',text:''}]})}>+ إضافة فقرة</button></section>}
 <section className="admin-form-section"><h2>المراجع والروابط</h2>{current.references?.map((ref,i)=><div className="admin-reference" key={i}><label>اسم المصدر<input value={ref.title} onChange={e=>update({references:current.references?.map((r,j)=>j===i?{...r,title:e.target.value}:r)})}/></label><label>رابط المصدر<input type="url" dir="ltr" placeholder="https://" value={ref.url} onChange={e=>update({references:current.references?.map((r,j)=>j===i?{...r,url:e.target.value}:r)})}/></label><button type="button" className="admin-link" onClick={()=>update({references:current.references?.filter((_,j)=>j!==i)})}>إزالة</button></div>)}<button type="button" className="admin-btn secondary" onClick={()=>update({references:[...(current.references||[]),{title:'',url:''}]})}>+ إضافة مصدر</button></section>
 <label className="admin-checkbox"><input type="checkbox" checked={!!current.sample} onChange={e=>update({sample:e.target.checked})}/> علّم هذا المحتوى كمثال تجريبي</label>
 </fieldset></form>}
 <div className="admin-savebar"><div><strong>{editor.kind==='articles'?'مقال':'برومبت'}</strong><span className="admin-date">{current.published?'منشور حاليًا':'مسودة'}</span></div><div className="admin-actions"><button className="admin-btn secondary" disabled={busy} onClick={()=>void save(false)}>{current.published?'إلغاء النشر وحفظ مسودة':'حفظ مسودة'}</button><button className="admin-btn" disabled={busy} onClick={()=>{const form=document.getElementById('content-editor') as HTMLFormElement|null;if(!form||form.reportValidity())void save(true)}}>{busy?'جارٍ الحفظ…':current.published?'حفظ التعديلات ونشرها':'نشر المحتوى'}</button></div></div>
 {editor.originalSlug&&current.published&&<div className="admin-actions admin-published-links"><a className="admin-link" href={`/${editor.kind}/${current.slug}`} target="_blank" rel="noreferrer">افتح الصفحة المنشورة ↗</a><button className="admin-link" onClick={()=>void copyLink()}>نسخ رابط الصفحة</button></div>}
 </>}
 </>}
 </div>
}

